version: "3.8"

services:
  app:
    build: .
    container_name: ci4_app
    ports:
      - "8086:80"
    volumes:
      - .:/var/www/html
      - ./apache-config:/etc/apache2/sites-available
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_produccion
    restart: always
    environment:
      POSTGRES_DB: control_produccion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: grupoes2023
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ci4_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8085:80"
    depends_on:
      - db

volumes:
  pg_data:
